//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlipFlash.Resources.strings {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlipFlash.Resources.strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add ähnelt.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Flashcard ähnelt.
        /// </summary>
        public static string Add_Flashcard {
            get {
                return ResourceManager.GetString("Add_Flashcard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Add Stack ähnelt.
        /// </summary>
        public static string Add_Stack {
            get {
                return ResourceManager.GetString("Add_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die All Flash Cards ähnelt.
        /// </summary>
        public static string All_Flash_Cards {
            get {
                return ResourceManager.GetString("All_Flash_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Answer ähnelt.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BACK SIDE ähnelt.
        /// </summary>
        public static string BACK_SIDE {
            get {
                return ResourceManager.GetString("BACK_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create ähnelt.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Day streak ähnelt.
        /// </summary>
        public static string Day_streak {
            get {
                return ResourceManager.GetString("Day_streak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DIFFICULTY ähnelt.
        /// </summary>
        public static string DIFFICULTY {
            get {
                return ResourceManager.GetString("DIFFICULTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discard ähnelt.
        /// </summary>
        public static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the answer or defination... ähnelt.
        /// </summary>
        public static string Enter_answer_definition {
            get {
                return ResourceManager.GetString("Enter_answer_definition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enter the question or term... ähnelt.
        /// </summary>
        public static string Enter_question_term {
            get {
                return ResourceManager.GetString("Enter_question_term", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expired flashcards ähnelt.
        /// </summary>
        public static string Expired_flashcards {
            get {
                return ResourceManager.GetString("Expired_flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Expiring today ähnelt.
        /// </summary>
        public static string Expiring_today {
            get {
                return ResourceManager.GetString("Expiring_today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die FRONT SIDE ähnelt.
        /// </summary>
        public static string FRONT_SIDE {
            get {
                return ResourceManager.GetString("FRONT_SIDE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In three weeks ähnelt.
        /// </summary>
        public static string In_Three_Weeks {
            get {
                return ResourceManager.GetString("In_Three_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die  In two weeks ähnelt.
        /// </summary>
        public static string In_Two_Weeks {
            get {
                return ResourceManager.GetString("In_Two_Weeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In {0} days ähnelt.
        /// </summary>
        public static string In_X_Days {
            get {
                return ResourceManager.GetString("In_X_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die In more than a month ähnelt.
        /// </summary>
        public static string InMoreThanAMonth {
            get {
                return ResourceManager.GetString("InMoreThanAMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Last Week ähnelt.
        /// </summary>
        public static string Last_Week {
            get {
                return ResourceManager.GetString("Last_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die My Stacks ähnelt.
        /// </summary>
        public static string My_Stacks {
            get {
                return ResourceManager.GetString("My_Stacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Next Week ähnelt.
        /// </summary>
        public static string Next_Week {
            get {
                return ResourceManager.GetString("Next_Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Question ähnelt.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die STACK ähnelt.
        /// </summary>
        public static string STACK {
            get {
                return ResourceManager.GetString("STACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Today ähnelt.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Todays flashcards ähnelt.
        /// </summary>
        public static string Todays_flashcards {
            get {
                return ResourceManager.GetString("Todays_flashcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tomorrow ähnelt.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unknown Stapel ähnelt.
        /// </summary>
        public static string Unknown_Stack {
            get {
                return ResourceManager.GetString("Unknown_Stack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {0} days ago ähnelt.
        /// </summary>
        public static string X_Days_Ago {
            get {
                return ResourceManager.GetString("X_Days_Ago", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yesterday ähnelt.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
